---
- name: Open Firewall
  firewalld:
    port: '{{item}}/tcp'
    permanent: true
    state: enabled
    zone: public
    immediate: yes
  with_items:
    - '{{firewall_ports}}'
  when: open_firewall
  ignore_errors: true


- name: Disabled Firewalld
  systemd:
    name: 'firewalld'
    state: stopped
    enabled: no
  when: disable_firewall
  ignore_errors: true
